# Generated by Django 5.1.6 on 2025-02-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=20, verbose_name='Прізвище')),
                ('phone_number', models.CharField(max_length=17, verbose_name='Номер телефону')),
                ('email', models.CharField(max_length=50, verbose_name='Електронна пошта')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slovo', models.CharField(max_length=20, verbose_name='Слово')),
                ('Perevod', models.CharField(max_length=15, verbose_name='Переклад')),
                ('languages', models.TextField(max_length=100, verbose_name='На яку мову перекладено')),
            ],
        ),
    ]
