# Generated by Django 5.1.6 on 2025-02-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_of_games',
            field=models.IntegerField(default=0),
        ),
    ]
