# Generated by Django 5.1.6 on 2025-02-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_count_of_games'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='word',
            table='user_word',
        ),
    ]
